import { Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, CalendarClock, CheckCircle2, CircleDashed, FileCheck2, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { buildDeadlines, buildMissions, buildReadiness, formatRemaining, type Mission, type RequirementStatusCount, type Urgency, type DashboardDocument } from "@/lib/command-center";
import type { TenderListItem } from "@/lib/tenders";
import { formatDate } from "@/lib/vault";

const URGENCY_DOT: Record<Urgency, string> = { high: "bg-destructive", medium: "bg-warning", low: "bg-info" };
const URGENCY_LABEL: Record<Urgency, string> = { high: "High priority", medium: "Attention", low: "Planned" };

function Metric({ label, value, hint, tone }: { label: string; value: string; hint?: string; tone?: "warning" | "danger" }) {
  return <div className="jasmiq-metric group rounded-2xl border border-white/65 bg-white/45 p-4 backdrop-blur-xl dark:bg-white/[0.04]"><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-muted-foreground">{label}</p><span className="mt-0.5 size-1.5 rounded-full bg-primary/45 transition-transform duration-500 group-hover:scale-150" /></div><p className={cn("mt-2 text-2xl font-semibold tracking-[-0.04em]", tone === "danger" && "text-destructive", tone === "warning" && "text-warning")}>{value}</p>{hint ? <p className="mt-1 text-xs leading-5 text-muted-foreground">{hint}</p> : null}</div>;
}

function MissionRow({ mission }: { mission: Mission }) {
  const remaining = formatRemaining(mission.deadline ?? null);
  return <li className="jasmiq-list-item group flex flex-col gap-3 border-b border-border/50 py-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><span className={cn("mt-2 size-2 shrink-0 rounded-full", URGENCY_DOT[mission.urgency])} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{mission.title}</p><span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">{URGENCY_LABEL[mission.urgency]}</span></div><p className="mt-1 text-sm leading-5 text-muted-foreground">{mission.detail}</p>{remaining ? <p className="mt-1 text-xs text-muted-foreground">{remaining}</p> : null}</div></div><Button asChild variant="outline" size="sm" className="w-full shrink-0 rounded-xl bg-white/50 transition-all duration-300 group-hover:border-primary/25 group-hover:bg-primary/[0.04] sm:w-auto"><Link to={mission.action.to}>{mission.action.label}<ArrowRight className="ml-1.5 size-3.5 transition-transform duration-300 group-hover:translate-x-0.5" /></Link></Button></li>;
}

interface CommandCenterProps { companyName: string | null; documents: DashboardDocument[]; tenders: TenderListItem[]; requirements: RequirementStatusCount[]; isLoading: boolean; hasError: boolean; onRetry: () => void; }

export function CommandCenter({ companyName, documents, tenders, requirements, isLoading, hasError, onRetry }: CommandCenterProps) {
  if (isLoading) return <section className="mb-6 space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[0,1,2,3].map((cell) => <Skeleton key={cell} className="h-28 rounded-2xl" />)}</div><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><Skeleton className="h-80 rounded-[2rem]" /><Skeleton className="h-80 rounded-[2rem]" /></div></section>;
  if (hasError) return <section className="glass-panel mb-6 flex flex-col items-center gap-3 p-10 text-center"><p className="text-sm font-medium">We couldn&apos;t load your intelligence center.</p><Button variant="outline" className="rounded-xl" onClick={onRetry}>Try again</Button></section>;

  const readiness = buildReadiness(documents, tenders, requirements);
  const missions = buildMissions(documents, tenders, requirements);
  const deadlines = buildDeadlines(tenders);
  const activeTenderIds = new Set(tenders.filter((t) => t.analysis_status !== "failed").map((t) => t.id));
  const activeRequirements = requirements.filter((row) => activeTenderIds.has(row.tender_id));
  const matched = activeRequirements.filter((row) => row.status === "matched").length;
  const total = activeRequirements.length;
  const review = activeRequirements.filter((row) => row.status === "manual_review" || row.status === "pending").length;
  const missing = activeRequirements.filter((row) => row.status === "missing").length;
  const readinessValue = readiness.tenderReadiness ?? 0;

  return <section className="mb-6 space-y-5">
    <div className="flex items-end justify-between gap-4 px-1"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary"><Sparkles className="size-3.5" /> Intelligence</div><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] sm:text-2xl">Your procurement command center</h2><p className="mt-1 text-sm text-muted-foreground">{companyName ?? "Current company"} · AI assists. You verify.</p></div><div className="hidden items-center gap-2 rounded-full border border-border/60 bg-white/45 px-3 py-1.5 text-xs text-muted-foreground shadow-sm backdrop-blur-xl sm:flex"><ShieldCheck className="size-3.5 text-success" /> Evidence-first</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active documents" value={String(readiness.activeDocuments)} hint={`${documents.length} total in vault`} /><Metric label="Expiring / expired" value={`${readiness.expiringDocuments} / ${readiness.expiredDocuments}`} hint="Next 30 days" tone={readiness.expiredDocuments > 0 ? "danger" : readiness.expiringDocuments > 0 ? "warning" : undefined} /><Metric label="Active tenders" value={String(readiness.activeTenders)} hint="Failed analyses excluded" /><Metric label="Tender readiness" value={readiness.tenderReadiness === null ? "—" : `${readinessValue}%`} hint={total > 0 ? `${matched} of ${total} requirements matched` : "Requirements not yet analyzed"} /></div>

    <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]">
      <div className="glass-panel overflow-hidden rounded-[2rem] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-muted-foreground">Readiness signal</p><p className="mt-1 text-lg font-semibold tracking-tight">Evidence coverage for active tenders</p></div><div className="jasmiq-status-chip"><CircleDashed className="size-3.5" /> Deterministic evidence</div></div>
        <div className="mt-6 grid items-center gap-6 sm:grid-cols-[170px_1fr]"><div className="mx-auto grid size-40 place-items-center rounded-full p-[7px] shadow-[0_20px_60px_-30px_rgba(37,99,235,0.55)]" style={{ background: `conic-gradient(var(--primary) ${readinessValue}%, color-mix(in oklab, var(--primary) 8%, transparent) 0)` }}><div className="grid size-full place-items-center rounded-full border border-white/70 bg-background/80 text-center backdrop-blur-xl dark:bg-background/70"><div><p className="text-4xl font-semibold tracking-[-0.06em]">{readiness.tenderReadiness === null ? "—" : `${readinessValue}%`}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">readiness</p></div></div></div>
          <div className="space-y-4"><div className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><FileCheck2 className="size-4 text-success" /> Matched evidence</span><strong>{matched}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted/80"><div className="jasmiq-progress h-full rounded-full" style={{ width: total ? `${Math.round((matched / total) * 100)}%` : "0%" }} /></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-border/50 bg-background/35 p-3"><p className="text-xs text-muted-foreground">Needs review</p><p className="mt-1 text-xl font-semibold">{review}</p></div><div className="rounded-2xl border border-border/50 bg-background/35 p-3"><p className="text-xs text-muted-foreground">Missing</p><p className="mt-1 text-xl font-semibold">{missing}</p></div></div></div>
        </div>
      </div>
      <div className="glass-panel rounded-[2rem] p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-muted-foreground">Signal</p><h3 className="mt-1 text-lg font-semibold tracking-tight">What needs attention</h3><div className="mt-5 space-y-3"><div className="rounded-2xl border border-border/50 bg-background/35 p-4"><p className="text-2xl font-semibold tracking-[-0.04em]">{missing}</p><p className="mt-1 text-sm text-muted-foreground">requirements missing</p></div><div className="rounded-2xl border border-border/50 bg-background/35 p-4"><p className="text-2xl font-semibold tracking-[-0.04em]">{review}</p><p className="mt-1 text-sm text-muted-foreground">requirements need verification</p></div><div className="rounded-2xl border border-border/50 bg-background/35 p-4"><p className="text-2xl font-semibold tracking-[-0.04em]">{readiness.expiringDocuments + readiness.expiredDocuments}</p><p className="mt-1 text-sm text-muted-foreground">documents need expiry attention</p></div></div></div>
    </div>

    <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="glass-panel rounded-[2rem] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-muted-foreground">Today</p><h3 className="mt-1 text-lg font-semibold tracking-tight">Mission queue</h3></div><span className="text-xs text-muted-foreground">{missions.length} active signal{missions.length === 1 ? "" : "s"}</span></div>{missions.length === 0 ? <div className="mt-4 flex items-start gap-3 rounded-2xl border border-success/20 bg-success/5 p-4"><CheckCircle2 className="mt-0.5 size-4 text-success" /><div><p className="text-sm font-semibold">You&apos;re all caught up.</p><p className="mt-1 text-sm text-muted-foreground">No urgent procurement actions require your attention.</p></div></div> : <ul className="mt-2">{missions.map((mission) => <MissionRow key={mission.id} mission={mission} />)}</ul>}</div>
      <div className="glass-panel rounded-[2rem] p-5 sm:p-6"><div className="flex items-center gap-2"><CalendarClock className="size-4 text-primary" /><h3 className="text-lg font-semibold tracking-tight">Upcoming deadlines</h3></div>{deadlines.length === 0 ? <div className="mt-4 rounded-2xl border border-border/50 bg-background/35 p-4"><p className="text-sm text-muted-foreground">No submission deadlines recorded yet.</p></div> : <ul className="mt-3 space-y-2">{deadlines.map((item) => <li key={item.id} className="rounded-2xl border border-border/50 bg-background/35 p-4 transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/20 hover:shadow-elegant"><p className="text-sm font-semibold">{item.entity ?? item.title}</p><p className="mt-1 text-xs text-muted-foreground">Submission deadline · {formatDate(item.deadline)}</p><p className={cn("mt-2 inline-flex items-center gap-1.5 text-xs font-semibold", item.urgency === "high" && "text-destructive", item.urgency === "medium" && "text-warning", item.urgency === "low" && "text-muted-foreground")}>{item.urgency === "high" ? <AlertTriangle className="size-3.5" /> : null}{item.remaining}</p></li>)}</ul>}</div>
    </div>
  </section>;
}
