/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTendersRouteImport } from './routes/_authenticated/tenders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedBankReferencesRouteImport } from './routes/_authenticated/bank-references'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTendersRoute = AuthenticatedTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankReferencesRoute =
  AuthenticatedBankReferencesRouteImport.update({
    id: '/bank-references',
    path: '/bank-references',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bank-references': typeof AuthenticatedBankReferencesRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/vault': typeof AuthenticatedVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bank-references': typeof AuthenticatedBankReferencesRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/vault': typeof AuthenticatedVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/bank-references': typeof AuthenticatedBankReferencesRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tenders': typeof AuthenticatedTendersRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/bank-references'
    | '/companies'
    | '/dashboard'
    | '/tenders'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/bank-references'
    | '/companies'
    | '/dashboard'
    | '/tenders'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/bank-references'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/tenders'
    | '/_authenticated/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders': {
      id: '/_authenticated/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AuthenticatedTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank-references': {
      id: '/_authenticated/bank-references'
      path: '/bank-references'
      fullPath: '/bank-references'
      preLoaderRoute: typeof AuthenticatedBankReferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBankReferencesRoute: typeof AuthenticatedBankReferencesRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTendersRoute: typeof AuthenticatedTendersRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBankReferencesRoute: AuthenticatedBankReferencesRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTendersRoute: AuthenticatedTendersRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
